# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e4f21c1599e783cf60157abb990cb214"
name = "Test Vercel Deployment 2"
handle = "test-vercel-deployment-2"
application_url = "https://answered-subscribe-promises-variety.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hugh-portfolio.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://answered-subscribe-promises-variety.trycloudflare.com/auth/callback",
  "https://answered-subscribe-promises-variety.trycloudflare.com/auth/shopify/callback",
  "https://answered-subscribe-promises-variety.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
